#### 原始网页：https://news.qq.com/zt2020/page/feiyan.htm#/
### 1. 数据提取部分

#### 1.1 导入模块

##### 如果使用本地静态资源，需要在头部声明

In [1]:
# # 只需要在顶部声明 CurrentConfig.ONLINE_HOST 即可(针对notebook)
# from pyecharts.globals import CurrentConfig, OnlineHostType
# # OnlineHostType.NOTEBOOK_HOST 默认值为 http://localhost:8888/nbextensions/assets/
# CurrentConfig.ONLINE_HOST = OnlineHostType.NOTEBOOK_HOST

In [2]:
import requests
import json
import time
import datetime
import pandas as pd

In [3]:
today = datetime.datetime.today()
date = f'{today.year}年{today.month}月{today.day}日'
date

'2021年8月5日'

#### 1.2 获取数据

In [4]:
url = f"https://view.inews.qq.com/g2/getOnsInfo?name=disease_h5&'{int(time.time()*1000)}'" 
response = requests.get(url)
datas = json.loads(response.json()['data'])
china_datas = datas['areaTree'][0]['children']
china_datas[:1]

[{'name': '台湾',
  'today': {'confirm': 32,
   'confirmCuts': 0,
   'isUpdated': True,
   'tip': '',
   'wzz_add': 0},
  'total': {'nowConfirm': 1961,
   'confirm': 15753,
   'suspect': 0,
   'dead': 791,
   'deadRate': '5.02',
   'showRate': False,
   'heal': 13001,
   'healRate': '82.53',
   'showHeal': True,
   'wzz': 0},
  'children': [{'name': '地区待确认',
    'today': {'confirm': 32, 'confirmCuts': 0, 'isUpdated': True},
    'total': {'nowConfirm': 1961,
     'confirm': 15753,
     'suspect': 0,
     'dead': 791,
     'deadRate': '5.02',
     'showRate': False,
     'heal': 13001,
     'healRate': '82.53',
     'showHeal': True,
     'wzz': 0}}]}]

#### 1.3 解析提取数据

In [5]:
data_set = []
for data in china_datas:
    data_dict = {
        'province': data['name'], 
        'nowConfirm': data['total']['nowConfirm'], 
        'confirm': data['total']['confirm'], 
        'dead': data['total']['dead'], 
        'heal': data['total']['heal'], 
        'deadRate': data['total']['deadRate'], 
        'healRate': data['total']['healRate'],
    } 
    data_set.append(data_dict)

#### 1.4 生成表格对象

In [6]:
df = pd.DataFrame(data_set) 
df

   province  nowConfirm  confirm  dead   heal deadRate healRate
0        台湾        1961    15753   791  13001     5.02    82.53
1        江苏         414     1166     0    752     0.00    64.49
2        云南         383      862     2    477     0.23    55.34
3        上海          69     2329     7   2253     0.30    96.74
4        广东          66     2896     8   2822     0.28    97.44
5        香港          63    11996   212  11721     1.77    97.71
6        湖南          52     1120     4   1064     0.36    95.00
7        福建          48      751     1    702     0.13    93.48
8        四川          42     1158     3   1113     0.26    96.11
9        河南          38     1355    22   1295     1.62    95.57
10       湖北          32    68211  4512  63667     6.61    93.34
11       天津          26      429     3    400     0.70    93.24
12       陕西          25      661     3    633     0.45    95.76
13       北京          22     1099     9   1068     0.82    97.18
14       浙江          20     1398     1   1377     0.07    98.50
15       山东          17      900     7    876     0.78    97.33
16      内蒙古          10      409     1    398     0.24    97.31
17       澳门           9       63     0     54     0.00    85.71
18       辽宁           8      438     2    428     0.46    97.72
19       甘肃           4      199     2    193     1.01    96.98
20       重庆           4      603     6    593     1.00    98.34
21       海南           2      190     6    182     3.16    95.79
22       广西           2      277     2    273     0.72    98.56
23       山西           1      254     0    253     0.00    99.61
24       吉林           1      574     3    570     0.52    99.30
25       宁夏           1       77     0     76     0.00    98.70
26       河北           0     1317     7   1310     0.53    99.47
27       西藏           0        1     0      1     0.00   100.00
28       江西           0      937     1    936     0.11    99.89
29      黑龙江           0     1612    13   1599     0.81    99.19
30       新疆           0      980     3    977     0.31    99.69
31       青海           0       18     0     18     0.00   100.00
32       安徽           0     1008     6   1002     0.60    99.40
33       贵州           0      147     2    145     1.36    98.64

#### 1.5 数据永久性保存

In [7]:
df.to_csv('./国内疫情数据.csv', encoding='utf-8-sig')

### 2. 可视化操作部分

#### 2.1 导入模块

In [8]:
from pyecharts import options as opts
from pyecharts.charts import Bar, Line, Pie, Grid, Map

#### 2.2 数据整理

In [9]:
df1 = df.sort_values(by=['nowConfirm'], ascending=False)[:10]
df1

  province  nowConfirm  confirm  dead   heal deadRate healRate
0       台湾        1961    15753   791  13001     5.02    82.53
1       江苏         414     1166     0    752     0.00    64.49
2       云南         383      862     2    477     0.23    55.34
3       上海          69     2329     7   2253     0.30    96.74
4       广东          66     2896     8   2822     0.28    97.44
5       香港          63    11996   212  11721     1.77    97.71
6       湖南          52     1120     4   1064     0.36    95.00
7       福建          48      751     1    702     0.13    93.48
8       四川          42     1158     3   1113     0.26    96.11
9       河南          38     1355    22   1295     1.62    95.57

#### 2.3 可视化饼图

##### 提示：可视化前，将数据转换为列表

In [10]:
lst = [list(i) for i in zip(df1['province'].values.tolist(),
                            df1['nowConfirm'].values.tolist())]
lst

[['台湾', 1961],
 ['江苏', 414],
 ['云南', 383],
 ['上海', 69],
 ['广东', 66],
 ['香港', 63],
 ['湖南', 52],
 ['福建', 48],
 ['四川', 42],
 ['河南', 38]]

In [11]:
pie = (
    Pie()
    .add("", lst, radius=["10%", "30%"])
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_省份占比'),
        legend_opts=opts.LegendOpts(orient="vertical", pos_top="70%", pos_left="70%"))
    .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}")))
pie.render_notebook()

#### 2.4可视化地图

In [12]:
df3 = df.sort_values(by=['nowConfirm'], ascending=False)[0:]
df3 = df3.drop(df3[df3['nowConfirm'] == 0].index)
lst = [list(i) for i in zip(df3['province'].values.tolist(),
                            df3['nowConfirm'].values.tolist())]
map = (
    Map()
    .add("", lst, 'china')
    .set_global_opts(
        title_opts=opts.TitleOpts(title=f'{date}_疫情分布'),
        visualmap_opts=opts.VisualMapOpts(
            max_=1000,
            min_=0,
            is_piecewise=False)
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
)
map.render_notebook()